<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/math.proto

namespace GPBMetadata\Proto;

class Math
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac6020a1070726f746f2f6d6174682e70726f746f120c73657276696365" .
            "2e6d61746822220a0a4164645265717565737412090a0178180120012805" .
            "12090a017918022001280522170a084164645265706c79120b0a0373756d" .
            "18012001280522270a0f53756274726163745265717565737412090a0178" .
            "18012001280512090a0179180220012805221d0a0d537562747261637452" .
            "65706c79120c0a04646966661801200128053291010a0a43616c63756c61" .
            "746f7212390a0361646412182e736572766963652e6d6174682e41646452" .
            "6571756573741a162e736572766963652e6d6174682e4164645265706c79" .
            "220012480a087375627472616374121d2e736572766963652e6d6174682e" .
            "5375627472616374526571756573741a1b2e736572766963652e6d617468" .
            "2e53756274726163745265706c7922004203d00201620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

